version: '3.8'
services:
  web:
    build: .
    ports:
      - "1557:1557"
    depends_on:
      - redis
    volumes:
      - ./templates:/app/templates
      - ./data:/app/data
      - ./static:/app/static
    environment:
      OPENAI_API_KEY: "OPENAI_API_KEY"
      FLASK_APP: "app"
      FLASK_RUN_HOST: 0.0.0.0

  redis:
    image: "redis:alpine"
    command: redis-server --port 6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    expose:
      - "6379:6379"